# Generated by Django 6.0.3 on 2026-03-15 00:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ttmmUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('CUSTOMER_ID', models.IntegerField(db_column='CUSTOMER_ID', primary_key=True, serialize=False)),
                ('EMAIL', models.EmailField(db_column='USER_EMAIL', max_length=100, unique=True)),
                ('USERNAME', models.CharField(db_column='USERNAME', max_length=50, unique=True)),
                ('First_Name', models.CharField(db_column='FIRST_NAME', max_length=50)),
                ('Last_Name', models.CharField(db_column='LAST_NAME', max_length=50)),
                ('is_staff', models.CharField(default='N', max_length=1)),
                ('is_superuser', models.CharField(default='N', max_length=1)),
                ('is_verified', models.CharField(default='N', max_length=1)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE')),
                ('CREATED_BY', models.CharField(db_column='CREATED_BY', max_length=100)),
                ('last_login', models.DateTimeField(auto_now=True, db_column='LAST_LOGIN')),
                ('Last_Updated_Date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('Last_Updated_By', models.CharField(db_column='LAST_UPDATED_BY', max_length=100)),
                ('auth_provider', models.CharField(db_column='AUTH_PROVIDER', default='USER_EMAIL', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='customer_set', related_query_name='customer', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customer_set', related_query_name='customer', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'ttmm_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
