# Generated by Django 6.0.3 on 2026-03-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttmmuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ttmmuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ttmmuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
