# Generated by Django 6.0.3 on 2026-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_ttmmuser_is_active_alter_ttmmuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttmmuser',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
